### ISSUE TITLE
Update chi import path

### ISSUE THREAD

**Issue by pkieltyka** [casbin/chi-authz#1]
Hey @hsluoyz can you update the chi import path in your test to "github.com/go-chi/chi" - also, the syntax for URL params changed from `:param` to `{param}` - otherwise will be compat

**Comment by hsluoyz** [comment]
Hi @pkieltyka ,

The new repo address has been updated. Also I added the new ``KeyMatch3()`` function to match the ``{param}`` style path. Thanks!
